CREATE DATABASE ID_CODING;
USE ID_CODING;

CREATE TABLE BOOKS (ID INT, NAME VARCHAR(255), AUTHOR VARCHAR(255), PAGE_COUNT INT);
INSERT INTO BOOKS (ID, NAME, AUTHOR, PAGE_COUNT) VALUES (1, 1984, 'George OrweLL', 317);
INSERT INTO BOOKS (ID, NAME, AUTHOR, PAGE_COUNT) VALUES (1, 'White chief', 'Mayne reed', 285);
SELECT * FROM BOOKS;


CREATE TABLE AUTHORS (ID INT, FCs VARCHAR(100), date_of_birth year;  date_of_dearth year);
INSERT INTO AUTHORS (ID, FCs, date_of_birth, date_of_dearth) VALUES (1, 'George OrweLL', 1818-04-04,
1883-10-22);
INSERT INTO AUTHORS (ID, FCs, date_of_birth, date_of_dearth) VALUES (2, 'Mayne reed', 1903-06-25
1950-04-21);
SELECT * FROM AUTHORS;


CREATE TABLE GENRES (ID INT, NAME_GENRES VARCHAR(255));
INSERT INTO GENRES (ID, NAME_GENRES) VALUES (1, 'Dystopian-novel');
INSERT INTO GENRES (ID, NAME_GENRES) VALUES (2, 'Foreign classics');
SELECT * FROM GENRES;